package TSP;

/**
 * AboutJDialog.java
 * A class representing the About used in a Simulating a 24 point card game.
 * <pre>
 *    Platform: jdk 1.8.0_14; NetBeans IDE 8.0.2; Windows 10
 *    Course: CS 142A
 *    Hours: 12 hours and 45 minutes
 *    Created on March 01, 2016, 6:45:39 PM
 *    Revised on March 02, 2016
 * </pre>
 *
 * @author:	Roman Barlet
 * @Author:     Henry Ang
 * @version: 	%I%
 * @see:     	javax.swing.JFrame
 * @see:        java.awt.Toolkit
 */
public class AboutJDialog extends javax.swing.JDialog
{

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method: AboutJJDialog
     * Description: Creates an instance of the AboutJJDialog
     * Date:   1/12/2016
     * </pre> 
     * @param   parent   Sets the frame style
     * @param   modal    Sets the Application    
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    public AboutJDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    AboutJDialog()
    {
        //To change body of generated methods, choose Tools | Templates.
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        aboutJScrollPane = new javax.swing.JScrollPane();
        aboutJTextArea = new javax.swing.JTextArea();
        closeJButton = new javax.swing.JButton();
        titleJLabel = new javax.swing.JLabel();
        infoJPanel = new javax.swing.JPanel();
        versionQueryJLabel = new javax.swing.JLabel();
        versionJLabel = new javax.swing.JLabel();
        vendorQueryJLabel = new javax.swing.JLabel();
        vendorJLabel = new javax.swing.JLabel();
        contactQueryJLabel = new javax.swing.JLabel();
        contactJLabel = new javax.swing.JLabel();
        copyrightQueryJLabel = new javax.swing.JLabel();
        copyrightJLabel = new javax.swing.JLabel();
        titleJSeparator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        setResizable(false);

        aboutJTextArea.setEditable(false);
        aboutJTextArea.setColumns(20);
        aboutJTextArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        aboutJTextArea.setRows(5);
        aboutJTextArea.setText("Welcome the the Cafe Dancers Database!\nThis program was created in order to properly organize and retain \ninformation on dancers!\nThis program has the capabilities to:\n• Print     • Clear    • Save    • Add Player\n• Edit Player   • Delete Player   • Display Statistics");
        aboutJScrollPane.setViewportView(aboutJTextArea);

        closeJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closeJButton.setText("Close");
        closeJButton.setToolTipText("Close the window");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        titleJLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleJLabel.setText("Cafe Dansa Database");

        infoJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout infoJPanelLayout = new java.awt.GridBagLayout();
        infoJPanelLayout.columnWidths = new int[] {0, 6, 0, 6, 0, 6, 0, 6, 0, 6, 0};
        infoJPanelLayout.rowHeights = new int[] {0, 6, 0, 6, 0};
        infoJPanelLayout.columnWeights = new double[] {0.5};
        infoJPanelLayout.rowWeights = new double[] {5.0};
        infoJPanel.setLayout(infoJPanelLayout);

        versionQueryJLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        versionQueryJLabel.setText("Product Version:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        infoJPanel.add(versionQueryJLabel, gridBagConstraints);

        versionJLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        versionJLabel.setText("1.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        infoJPanel.add(versionJLabel, gridBagConstraints);

        vendorQueryJLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        vendorQueryJLabel.setText("Vendor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        infoJPanel.add(vendorQueryJLabel, gridBagConstraints);

        vendorJLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        vendorJLabel.setText("Roman Barlet");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        infoJPanel.add(vendorJLabel, gridBagConstraints);

        contactQueryJLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        contactQueryJLabel.setText("Contact:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        infoJPanel.add(contactQueryJLabel, gridBagConstraints);

        contactJLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        contactJLabel.setText("Roman.Barlet@email.edcc.edu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        infoJPanel.add(contactJLabel, gridBagConstraints);

        copyrightQueryJLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        copyrightQueryJLabel.setText("CopyRight:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        infoJPanel.add(copyrightQueryJLabel, gridBagConstraints);

        copyrightJLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        copyrightJLabel.setText("Free");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        infoJPanel.add(copyrightJLabel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aboutJScrollPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleJLabel)
                            .addComponent(infoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJLabel)
                .addGap(5, 5, 5)
                .addComponent(titleJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(aboutJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeJButtonActionPerformed
    {//GEN-HEADEREND:event_closeJButtonActionPerformed
        // Disposes the Employee about form
        this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre0
     * Method:      main
     * Description: Displays the instance of the SolutionJDialog
     * Date:        1/12/2016
     * </pre> 
     * @param   args[]  Initializes the JDialog
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AboutJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane aboutJScrollPane;
    private javax.swing.JTextArea aboutJTextArea;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel contactJLabel;
    private javax.swing.JLabel contactQueryJLabel;
    private javax.swing.JLabel copyrightJLabel;
    private javax.swing.JLabel copyrightQueryJLabel;
    private javax.swing.JPanel infoJPanel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JSeparator titleJSeparator;
    private javax.swing.JLabel vendorJLabel;
    private javax.swing.JLabel vendorQueryJLabel;
    private javax.swing.JLabel versionJLabel;
    private javax.swing.JLabel versionQueryJLabel;
    // End of variables declaration//GEN-END:variables
}
